# Task: xArm strawberry-picking  – 2-D RGB-only dataset
name:           xarm_baseline_2d       # shows up in log dirs
task_name:      xarm_baseline_2d

# ------------------------------------------------------------------
dataset:
  _target_: diffusion_policy.dataset.xarm_2d_dataset.XArmImageDataset2D
  zarr_path: /home/alex/Documents/3D-Diffusion-Policy/dt_ag/data/2d_strawberry_baseline/4_cam_baseline_zarr_rs_side+front_no_crop
  shape_meta: ${shape_meta}
  horizon: 8                     # obs window
  pad_before: 0                  # default for image dataset
  pad_after: 0
  seed: 42
  val_ratio: 0.0
  max_train_episodes: null

env_runner: null                 # offline BC only

# ------------------------------------------------------------------
# Shapes for encoder and diffusion head
shape_meta: &shape_meta
  obs:
    rs_side_rgb:
      shape: [3, 160, 220]       # (C,H,W) after your resize script
      type: rgb
    rs_front_rgb:
      shape: [3, 160, 220]       # (C,H,W) after your resize script
      type: rgb
    # # rs_wrist_rgb:
    # #   shape: [3, 240, 360]       # (C,H,W) after your resize script
    # #   type: rgb
    # zed_rgb:
    #   shape: [3, 160, 220]       # (C,H,W) after your resize script
    #   type: rgb
    pose:
      shape: [10]                 # x y z 6d_pose gripper

  action:
    shape: [10]
